# Project Information
site_name: Omnissa Developer Portal
site_url: https://euc-dev.github.io
site_author: Phil Helmling
site_description: POC for developer.omnissa.com
docs_dir: docs
site_dir: .site
use_directory_urls: true

# Repository
repo_url: https://github.com/euc-dev/euc-dev.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2005-2024 Broadcom. All rights reserved.<br/>
  The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.<br/><br/>

# Configuration
theme:
  name: material
  custom_dir: overrides
  favicon: assets/logos/favicon-light.svg
  logo: assets/logos/favicon-dark.svg
  admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
    annotation: material/circle-medium
    annotation: material/record-circle
    annotation: material/arrow-right-circle
    annotation: material/arrow-right-circle-outline
    annotation: material/chevron-right-circle
    annotation: material/star-four-points-circle
    annotation: material/plus-circle-outline
  palette:
    scheme: omnissa
    primary: dark-shade-blue
    accent: neon

  # Palette toggle for automatic mode
  # - media: "(prefers-color-scheme)"
  #   scheme: omnissa
  #   toggle:
  #     icon: material/lightbulb-auto-outline
  #     name: Switch to light mode
  # Palette toggle for light mode
  # - media: "(prefers-color-scheme: light)"
  #   scheme: slate
  #   primary: dark-shade-blue
  #   accent: neon
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Dark Theme
  # Palette toggle for dark mode
  # - media: "(prefers-color-scheme: dark)"
  #   scheme: omnissa
  #   primary: dark-shade-blue
  #   accent: neon
  #   toggle:
  #     icon: material/toggle-switch-off-outline
  #     name: Light Theme
  font:
    text: Outfit
    code: Poppins
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.header
  - navigation.indexes
  - navigation.instant
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - open-in-new-tab
  - markdownextradata:
      jinja_options:
        variable_start_string: "${{"
        variable_end_string: "}}"
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: false
      exclude:
        - index.md
      fallback_to_build_date: true
      type: timeago
  - swagger-ui-tag
  - monorepo
  - macros

# Customization
extra:
  homepage: https://omnissa.com

analytics: 
  provider: custom
  property: foobar
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback!
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >- 
          Thanks for your feedback! Please provide some specifics by providing additional info in a new Issue:
          https://github.com/euc-dev/euc-dev.github.io/issues/new/?title=[Feedback]+{title}+-+{url}

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/footer.Cx6ysBfj.css
  - assets/stylesheets/mkdocsoad.css
  - assets/stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - assets/javascripts/tablesort.min.js #https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - neoteroi.spantable
  - neoteroi.cards
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
        - material/.icons
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - Home:
    - ./index.md
  - Dev Centre:
    - ./dev-centre/index.md
  - Product Docs:
    - ./product-docs/index.md
  - APIs: '*include ./apis/*/mkdocs.yml'
  - Code Samples: '*include ./samples/*/mkdocs.yml'
  - PowerCLI: '*include ./powercli/*/mkdocs.yml'
  - Terraform: '*include ./terraform/*/mkdocs.yml'
  - SDKs: '*include ./sdks/*/mkdocs.yml'
  - Support:
    - ./support/index.md
  - About:
    - ./about/index.md
